const byId = (id) => document.getElementById(id);

export const els = {
  track: byId('track'),
  ghost: byId('ghost'),
  tipStart: byId('tipStart'),
  tipEnd: byId('tipEnd'),
  tipCenter: byId('tipCenter'),
  ticks: byId('ticks'),
  rows: byId('rows'),
  empty: byId('empty'),
  modal: byId('modal'),
  startField: byId('startField'),
  endField: byId('endField'),
  bucketField: byId('bucketField'),
  noteField: byId('noteField'),
  notePreview: byId('notePreview'),
  notePreviewToggle: byId('notePreviewToggle'),
  modalForm: byId('modalForm'),
  modalCancel: byId('modalCancel'),
  modalClose: byId('modalClose'),
  modalTitle: document.querySelector('.modal-title'),
  modalFooter: document.querySelector('.modal-footer'),
  modalDelete: byId('modalDelete'),
  modalStatusWrap: byId('modalStatusWrap'),
  modalStatusBtn: byId('modalStatusBtn'),
  modalStatusMenu: byId('modalStatusMenu'),
  // Recurrence controls
  repeatEnabled: byId('repeatEnabled'),
  repeatFields: byId('repeatFields'),
  repeatFreq: byId('repeatFreq'),
  repeatUntil: byId('repeatUntil'),
  repeatUntilWrap: byId('repeatUntilWrap'),
  repeatDowWrap: byId('repeatDowWrap'),
  repeatDow: byId('repeatDow'),
  btnDowWeekdays: byId('btnDowWeekdays'),
  btnDowAll: byId('btnDowAll'),
  applyScopeWrap: byId('applyScopeWrap'),
  applyScopeOne: byId('applyScopeOne'),
  applyScopeSeries: byId('applyScopeSeries'),
  extendWrap: byId('extendWrap'),
  extendUntil: byId('extendUntil'),
  btnExtendSeries: byId('btnExtendSeries'),
  total: byId('total'),
  toast: byId('toast'),
  viewHelp: byId('viewHelp'),
  view24: byId('view24'),
  viewDefault: byId('viewDefault'),
  // Calendar / header controls
  btnCalendar: byId('btnCalendar'),
  btnCalendar2: byId('btnCalendar2'),
  btnCalendarFab: byId('btnCalendarFab'),
  dayLabel: byId('dayLabel'),
  calendarCard: byId('calendarCard'),
  calendarGrid: byId('calendarGrid'),
  calWeekdays: byId('calWeekdays'),
  calMonthLabel: byId('calMonthLabel'),
  calPrev: byId('calPrev'),
  calNext: byId('calNext'),
  // Mobile controls
  mobileControls: byId('mobileControls'),
  mobileScrollbar: byId('mobileScrollbar'),
  mobileWindow: byId('mobileWindow'),
  mobileZoomIn: byId('mobileZoomIn'),
  mobileZoomOut: byId('mobileZoomOut'),
  // Bucket reports
  bucketDayCard: byId('bucketDayCard'),
  bucketDayBody: byId('bucketDayBody'),
  bucketDayEmpty: byId('bucketDayEmpty'),
  bucketMonthCard: byId('bucketMonthCard'),
  bucketMonthBody: byId('bucketMonthBody'),
  bucketMonthEmpty: byId('bucketMonthEmpty'),
  bucketMonthTitle: byId('bucketMonthTitle'),
  // Settings
  btnSettings: byId('btnSettings'),
  settingsModal: byId('settingsModal'),
  settingsClose: byId('settingsClose'),
  settingsCancel: byId('settingsCancel'),
  btnExport: byId('btnExport'),
  btnImport: byId('btnImport'),
  importFile: byId('importFile'),
  btnEraseAll: byId('btnEraseAll'),
  themeSelect: byId('themeSelect'),
  lblBackup: byId('lblBackup'),
  lblRestore: byId('lblRestore'),
};
