const byId = (id) => document.getElementById(id);

export const els = {
  track: byId('track'),
  ghost: byId('ghost'),
  tipStart: byId('tipStart'),
  tipEnd: byId('tipEnd'),
  tipCenter: byId('tipCenter'),
  ticks: byId('ticks'),
  rows: byId('rows'),
  empty: byId('empty'),
  // Collapsible sections
  entriesCard: byId('entriesCard'),
  entriesToggle: byId('entriesToggle'),
  entriesBody: byId('entriesBody'),
  modal: byId('modal'),
  startField: byId('startField'),
  endField: byId('endField'),
  bucketField: byId('bucketField'),
  // Prefer new dual-editor note field when present
  noteField: document.getElementById('noteField2') || byId('noteField'),
  notePreview: document.getElementById('notePreview2') || byId('notePreview'),
  notePreviewToggle: document.getElementById('notePreviewToggle2') || byId('notePreviewToggle'),
  // Bucket persistent note (edit modal)
  bucketNoteField: byId('bucketNoteField'),
  bucketNotePreview: byId('bucketNotePreview'),
  bucketNotePreviewToggle: byId('bucketNotePreviewToggle'),
  modalForm: byId('modalForm'),
  modalCancel: byId('modalCancel'),
  modalClose: byId('modalClose'),
  modalTitle: document.querySelector('.modal-title'),
  modalFooter: document.querySelector('.modal-footer'),
  modalDelete: byId('modalDelete'),
  modalStatusWrap: byId('modalStatusWrap'),
  modalStatusBtn: byId('modalStatusBtn'),
  modalStatusMenu: byId('modalStatusMenu'),
  // Schedule in edit modal
  scheduleField: byId('scheduleField'),
  scheduleList: byId('scheduleList'),
  // Note modal
  noteModal: byId('noteModal'),
  noteModalTitle: document.getElementById('noteModalTitle'),
  noteModalClose: byId('noteModalClose'),
  // Punch note viewer/editor (note modal)
  noteViewer: byId('noteViewer'),
  noteEditorWrap: byId('noteEditorWrap'),
  noteEditor: byId('noteEditor'),
  // Bucket note viewer/editor (note modal)
  bucketNoteViewer: byId('bucketNoteViewer'),
  bucketNoteEditorWrap: byId('bucketNoteEditorWrap'),
  bucketNoteEditor: byId('bucketNoteEditor'),
  noteEditToggle: byId('noteEditToggle'),
  noteSave: byId('noteSave'),
  noteCancel: byId('noteCancel'),
  // Recurrence controls
  repeatEnabled: byId('repeatEnabled'),
  repeatFields: byId('repeatFields'),
  repeatFreq: byId('repeatFreq'),
  repeatUntil: byId('repeatUntil'),
  repeatUntilWrap: byId('repeatUntilWrap'),
  repeatDowWrap: byId('repeatDowWrap'),
  repeatDow: byId('repeatDow'),
  btnDowWeekdays: byId('btnDowWeekdays'),
  btnDowAll: byId('btnDowAll'),
  applyScopeWrap: byId('applyScopeWrap'),
  applyScopeOne: byId('applyScopeOne'),
  applyScopeSeries: byId('applyScopeSeries'),
  extendWrap: byId('extendWrap'),
  extendUntil: byId('extendUntil'),
  btnExtendSeries: byId('btnExtendSeries'),
  total: byId('total'),
  toast: byId('toast'),
  viewHelp: byId('viewHelp'),
  btnBucketBackTop: byId('btnBucketBackTop'),
  view24: byId('view24'),
  viewDefault: byId('viewDefault'),
  btnCopyChart: byId('btnCopyChart'),
  // Calendar / header controls
  btnCalendar: byId('btnCalendar'),
  btnCalendar2: byId('btnCalendar2'),
  btnCalendarFab: byId('btnCalendarFab'),
  btnCopyChartTop: byId('btnCopyChartTop'),
  btnCopyChartTable: byId('btnCopyChartTable'),
  dayLabel: byId('dayLabel'),
  calendarCard: byId('calendarCard'),
  // Dashboard
  dashboardCard: byId('dashboardCard'),
  dashboardGrid: byId('dashboardGrid'),
  btnDashboard: byId('btnDashboard'),
  btnCustomizeDay: byId('btnCustomizeDay'),
  btnCustomizeMonth: byId('btnCustomizeMonth'),
  btnAddModule: byId('btnAddModule'),
  // Day View modular
  dayDashboardCard: byId('dayDashboardCard'),
  dayDashboardGrid: byId('dayDashboardGrid'),
  btnAddDayModule: byId('btnAddDayModule'),
  // Month View modular
  monthDashboardCard: byId('monthDashboardCard'),
  monthDashboardGrid: byId('monthDashboardGrid'),
  btnAddMonthModule: byId('btnAddMonthModule'),
  calendarGrid: byId('calendarGrid'),
  calWeekdays: byId('calWeekdays'),
  calMonthLabel: byId('calMonthLabel'),
  calPrev: byId('calPrev'),
  calNext: byId('calNext'),
  // Mobile controls
  mobileControls: byId('mobileControls'),
  mobileScrollbar: byId('mobileScrollbar'),
  mobileWindow: byId('mobileWindow'),
  mobileZoomIn: byId('mobileZoomIn'),
  mobileZoomOut: byId('mobileZoomOut'),
  mobileZoomRange: byId('mobileZoomRange'),
  // Bucket reports
  bucketDayCard: byId('bucketDayCard'),
  bucketDayToggle: byId('bucketDayToggle'),
  bucketDayBody: byId('bucketDayBody'),
  bucketDayEmpty: byId('bucketDayEmpty'),
  bucketMonthCard: byId('bucketMonthCard'),
  bucketMonthBody: byId('bucketMonthBody'),
  bucketMonthEmpty: byId('bucketMonthEmpty'),
  bucketMonthTitle: byId('bucketMonthTitle'),
  // Bucket view
  bucketViewCard: byId('bucketViewCard'),
  bucketViewTitle: byId('bucketViewTitle'),
  bucketViewTotal: byId('bucketViewTotal'),
  bucketViewBody: byId('bucketViewBody'),
  bucketViewEmpty: byId('bucketViewEmpty'),
  btnBucketBack: byId('btnBucketBack'),
  btnBucketDelete: byId('btnBucketDelete'),
  // Settings
  btnSettings: byId('btnSettings'),
  settingsModal: byId('settingsModal'),
  settingsClose: byId('settingsClose'),
  settingsCancel: byId('settingsCancel'),
  btnExport: byId('btnExport'),
  btnImport: byId('btnImport'),
  importFile: byId('importFile'),
  btnEraseAll: byId('btnEraseAll'),
  themeSelect: byId('themeSelect'),
  lblBackup: byId('lblBackup'),
  lblRestore: byId('lblRestore'),
  // Settings: schedules and dashboard
  settingsSchedList: byId('settingsSchedList'),
  settingsAddSched: byId('settingsAddSched'),
  settingsRenameSched: byId('settingsRenameSched'),
  settingsDeleteSched: byId('settingsDeleteSched'),
  settingsMoveFrom: byId('settingsMoveFrom'),
  settingsMoveTo: byId('settingsMoveTo'),
  settingsMoveStart: byId('settingsMoveStart'),
  settingsMoveEnd: byId('settingsMoveEnd'),
  settingsMoveBtn: byId('settingsMoveBtn'),
  settingsCustomizeDashboard: byId('settingsCustomizeDashboard'),
  settingsSchedName: byId('settingsSchedName'),
  settingsSchedMsg: byId('settingsSchedMsg'),
  settingsDeleteConfirm: byId('settingsDeleteConfirm'),
  settingsDeleteConfirmText: byId('settingsDeleteConfirmText'),
  settingsDeleteYes: byId('settingsDeleteYes'),
  settingsDeleteNo: byId('settingsDeleteNo'),
  // Schedules
  scheduleSelect: byId('scheduleSelect'),
  btnAddSchedule: byId('btnAddSchedule'),
  btnRenameSchedule: byId('btnRenameSchedule'),
  btnDeleteSchedule: byId('btnDeleteSchedule'),
  // Module modal
  moduleModal: byId('moduleModal'),
  moduleClose: byId('moduleClose'),
  moduleCancel: byId('moduleCancel'),
  moduleForm: byId('moduleForm'),
  moduleType: byId('moduleType'),
  moduleTitle: byId('moduleTitle'),
  moduleScheduleList: byId('moduleScheduleList'),
};
